<?php
/**
 * Created by PhpStorm.
 * User: lzm
 * Date: 2018/6/2
 * Time: 11:06
 */

namespace app\index\model;
use think\Model;
use think\Db;
$db = null;

class InfoTable extends Model
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

//        $db = new Db();
    }
}